/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package latihanjavafx;

/**
 *
 * @author Hafiyyan Faza XIR5
 */
public class FrameIdealTubuh extends javax.swing.JFrame {

    /**
     * Creates new form FrameIdealTubuh
     */
    public FrameIdealTubuh() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jeniskelamin = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rdperem = new javax.swing.JRadioButton();
        rdlaki = new javax.swing.JRadioButton();
        buttonhitung = new javax.swing.JButton();
        buttonulang = new javax.swing.JButton();
        buttonkeluar = new javax.swing.JButton();
        idnama = new javax.swing.JTextField();
        idtinggi = new javax.swing.JTextField();
        idberat = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        hasil1 = new javax.swing.JTextField();
        hasil2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        idideal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 102));
        setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(43, 93, 40, 14);

        jLabel3.setText("Tinggi");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(43, 133, 40, 14);

        jLabel4.setText("Berat");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(43, 171, 40, 14);

        jLabel5.setText("Jenis Kelamin");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(91, 210, 90, 20);

        jeniskelamin.add(rdperem);
        rdperem.setText("Perempuan");
        rdperem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdperemActionPerformed(evt);
            }
        });
        getContentPane().add(rdperem);
        rdperem.setBounds(304, 206, 110, 23);

        jeniskelamin.add(rdlaki);
        rdlaki.setText("Laki-Laki");
        rdlaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdlakiActionPerformed(evt);
            }
        });
        getContentPane().add(rdlaki);
        rdlaki.setBounds(206, 206, 80, 23);

        buttonhitung.setText("Hitung");
        buttonhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonhitungActionPerformed(evt);
            }
        });
        getContentPane().add(buttonhitung);
        buttonhitung.setBounds(101, 258, 80, 23);

        buttonulang.setText("Coba Ulang");
        buttonulang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonulangActionPerformed(evt);
            }
        });
        getContentPane().add(buttonulang);
        buttonulang.setBounds(199, 258, 100, 23);

        buttonkeluar.setText("Keluar");
        buttonkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonkeluarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonkeluar);
        buttonkeluar.setBounds(307, 258, 90, 23);

        idnama.setToolTipText("");
        getContentPane().add(idnama);
        idnama.setBounds(118, 80, 220, 30);
        getContentPane().add(idtinggi);
        idtinggi.setBounds(116, 120, 220, 30);
        getContentPane().add(idberat);
        idberat.setBounds(116, 168, 220, 30);

        jLabel7.setText("Kg");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(366, 304, 60, 30);

        jLabel8.setText("Kg");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(354, 171, 23, 14);

        jLabel9.setText("Cm");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(354, 133, 23, 14);

        hasil1.setText("?");
        getContentPane().add(hasil1);
        hasil1.setBounds(118, 394, 260, 40);

        hasil2.setText("?");
        getContentPane().add(hasil2);
        hasil2.setBounds(58, 442, 360, 30);

        jLabel10.setText("Hasil Analisa Kesehatan");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(118, 372, 170, 14);

        jPanel1.setBackground(new java.awt.Color(153, 255, 102));

        idideal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ididealActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("SF Sports Night", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setText("           Aplikasi Menuju Tubuh Ideal");

        jLabel6.setText("Berat Badan Ideal Anda Adalah");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(idideal, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 237, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idideal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(153, 153, 153))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 470, 490);

        setSize(new java.awt.Dimension(487, 523));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rdperemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdperemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdperemActionPerformed

    private void rdlakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdlakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdlakiActionPerformed

    private void ididealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ididealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ididealActionPerformed

    private void buttonkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonkeluarActionPerformed
        dispose();
        System.exit(0);
        
    }//GEN-LAST:event_buttonkeluarActionPerformed

    private void buttonulangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonulangActionPerformed
       idnama.setText("");
       idberat.setText("");
       idtinggi.setText("");
       idideal.setText("");
       hasil1.setText("");
       hasil2.setText("");
       jeniskelamin.clearSelection();
    }//GEN-LAST:event_buttonulangActionPerformed

    private void buttonhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonhitungActionPerformed
        double t = Double.valueOf(idtinggi.getText());
        double b = Double.valueOf(idberat.getText());
        double h = 0;
        String nama = idnama.getText();
        
        if(rdlaki.isSelected()){
            h = (t-100);
        }
        else if(rdperem.isSelected()){
            h = (t-104);
        }
        
        String temp = Double.toString(h);
        
        if(h<b){
        idideal.setText(temp);
        hasil1.setText("Maaf "+nama+" Sepertinya anda Overweight");
        hasil2.setText("Saran kami kepada yth "+nama+" lebih keraslah berolahlaga lagi");
        }
        else if(h>b){
        idideal.setText(temp);
        hasil1.setText("Maaf "+nama+" Underweight");
        hasil2.setText("Saran kami kepada yth "+nama+" makanlah makanan yang berlemak");
        }
        else{
           idideal.setText(temp);
           hasil1.setText("Selamat "+nama+" Anda Ideal");
           hasil2.setText("Saran kami kepada yth "+nama+" pertahankan fisik anda");
        }
    }//GEN-LAST:event_buttonhitungActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameIdealTubuh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameIdealTubuh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameIdealTubuh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameIdealTubuh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameIdealTubuh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonhitung;
    private javax.swing.JButton buttonkeluar;
    private javax.swing.JButton buttonulang;
    private javax.swing.JTextField hasil1;
    private javax.swing.JTextField hasil2;
    private javax.swing.JTextField idberat;
    private javax.swing.JTextField idideal;
    private javax.swing.JTextField idnama;
    private javax.swing.JTextField idtinggi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.ButtonGroup jeniskelamin;
    private javax.swing.JRadioButton rdlaki;
    private javax.swing.JRadioButton rdperem;
    // End of variables declaration//GEN-END:variables
}
